- hosts: leandronsp
  gather_facts: no
  vars:
    application: saas_b2b_boilerplate_api
    stage: production
    home_path: /home/ubuntu
    root_path: '{{home_path}}/saas-b2b-boilerplate-api'
    domain_name: api.leandronsp.com
    protocol: http

  roles:
    - ./roles/common
    - ./roles/python
    - ./roles/postgres
    - ./roles/nodejs
    - ./roles/ruby
    - ./roles/rails-app
    - ./roles/nginx-api
